### ISSUE TITLE
VS 2015 build issues

### ISSUE THREAD

**Issue by timokreuzer** [01org/hyperscan#14]
There are some issues with the build on VS 2015:
- On Win32 target (when Debug buid is selected) all functions that have 256 bit aligned parameters resut in build error, these can be fixed by adding the vectorcall calling convenion to these functions.
- Win32 VS compatible clz64 and ctz64 are missing (there is no BitScan*64 intrinsic for Win32 target). Can be fixed by using 2 32 bit BitScan*.
- Adding alignment to u64a/s64a causes issues on Win32 target when they are used as parameters. The alignment is not required, since these types are automatically aligned on the stack.
- Some warining parameters are broken
- __popcnt64 doesn't exist on Win32 target

**Comment by mdb256** [comment]
Thanks for your patches - we will take a look through them. Some we should be able to use directly, others will need some more thought.

But on one of your points: alignment for u64a is required, as these are values used not just on the stack, but also in structures, and we need to retain their alignment for 32 and 64 bit compatibility of these structures.

**Comment by timokreuzer** [comment]
Thank you for your quick response. Regarding the alignment of data types on Visual Studio: While https://msdn.microsoft.com/en-us/library/83ythb65.aspx suggests that the alignment for 32 bit is 4 bytes, the default is actually 8: The option to specify minimum structure packing is /Zp*, where /Zp8 is the default (https://msdn.microsoft.com/en-us/library/xh3e3fd0.aspx). I have verified that with #pragma pack(show). To ensure this a static assert can be used.

**Comment by timokreuzer** [comment]
Updated patch:
[patch2.zip](https://github.com/01org/hyperscan/files/202476/patch2.zip)

**Comment by timokreuzer** [comment]
New (updated) patch better addressing alignment on x86. While 64 bit variables are properly aligned on the stack as well as in structures on x86 VS builds, they won't be when passed as parameters to non-inlined functions. This is most likely also true for GCC, unless GCC copies the parameter to an aligned location on the stack, creating additional overhead. Since the compiler should be able to decide on it's own, when to align data for performance, I added unaligned u64/s64 types and replaced all aligned ones in parameters with them. 
[patch.zip](https://github.com/01org/hyperscan/files/206462/patch.zip)

**Comment by hughesac** [comment]
I'm also having trouble with the Visual Studio 2015 build.  I'm trying it with Hyper 4.3.1 and boost 1.59.0.  I built and installed Ragel in cygwin and  used cmake-gui to generate the Visual Studio solution.  I get syntax errors on these lines

https://github.com/01org/hyperscan/blob/v4.3.1/src/util/simd_utils.c#L35
https://github.com/01org/hyperscan/blob/v4.3.1/src/util/simd_utils.c#L51

I got past those errors by changing those lines to use the same syntax as this line
https://github.com/01org/hyperscan/blob/v4.3.1/src/fdr/fdr.c#L83

I was able to build successfully after that in release and debug for 64-bit.  However I can only get the unit tests to run with a debug build but there are thousands of errors.  When I try to run the unit tests with the release build there is an immediate invalid instruction exception before any tests actually start running.  I get the same invalid instruction exception when I try to run my code linked against hs.lib.

I'm guessing I have done something wrong since it sounds like other people have had success building Hyperscan using Visual Studio.

**Comment by mdb256** [comment]
If you are able to, could you try the develop branch? We have fixed a few issues related to building and running with VS2015 since 4.3.1, and these commits will be in v4.4.

These issues include the ones you've noted, and 1a24b0b should fix the errors running the debug build. Be warned, running the unit tests in the VS debugger with the debug runtime libs takes a long time.

We are still finding problems compiling C++ with MSVC, as they still have a few compatibility issues with C++11. The current VS2017 RC also fails right now - we will look at that. Also, use of AVX is hardcoded in CMakeLists.txt. If you have a more recent machine this can be changed to AVX2 either in the cmake file, or in the project settings.

**Comment by hughesac** [comment]
With the develop branch as of January 5 I was able to build with just one error in hsbench about getopt.  That didn't stop the build of everything else.  I had to download sqlite3 and put it into the hyperscan base directory to get cmake to finish configuration.  

I'm still getting the illegal instruction exception when running the unit tests.

I'm doing all of this testing in a VM but I don't think that would matter.since all of the required CPU features are available.  Let me know if there is any more useful information that I could provide.

**Comment by mdb256** [comment]
Our tools are primarily for Unix/Linux builds, and we currently don't have a good solution for getopt for Windows builds. I should at least ensure that MSVC builds 

What machine is hosting the VM, and what are you using for virtualisation?
